route:
  receiver: webhook
  group_by: [alertname]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: webhook
    webhook_configs:
      - url: "http://127.0.0.1:5001/alerts"
        send_resolved: true
